host: 127.0.0.1 # IP-адрес сервера
port: 25565 # Порт сервера
proxy: BOTH # Тип используемых прокси | SOCKS, HTTP, BOTH, NONE
duration: 60 # Длительность атаки | секунды
threads: 100 # Количество потоков для отправки ботов | Потоки запускаются со скоростью: 20/сек
delay: 50 # Задержка отправки ботов для каждого потока | миллисекунды
nicks: LIST # Тип ников | LIST, ALTS или RANDOM
listen: true # Отслеживать состояние бота и иметь возможность осуществлять действия
ping: true # Активировать модуль спама пинг-пакетами
join: true # Активировать модуль спама ботами
chat: true # Выводить чат сервера
info: 0 # Способ вывода информации | 0 или 1
stay: true # Удерживать ботов на сервере
actions: # Выполнять определённые действия на сервере | количество_выполнений;задержка;действие;аргументы
  - 1;2000;chat;/register bot12345 bot12345
  - 1;3000;chat;/login bot12345
  - 2;3500;move;true
  - 5;4000;use;MAIN_HAND
  - 3;4000;use;OFF_HAND
  - 1;4500;chat;/warp shop
  - 1;5000;chat;Всем привет!
  - 2;5100;swap
  - 1;5200;slot;0
  - 1;5300;drop;
  - 1;5400;slot;1
  - 1;5500;drop;
  - 1;5600;slot;2
  - 1;5700;drop;
  - 1;5800;slot;3
  - 1;5900;drop;
  - 1;6000;slot;4
  - 1;6100;drop;
  - 1;6200;slot;5
  - 1;6300;drop;
  - 1;6400;slot;6
  - 1;6500;drop;
  - 1;6600;slot;7
  - 1;6700;drop;
  - 1;6800;slot;8
  - 1;6900;drop;